//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsSP.Layouts {
    
    
    public partial class LatestFiles {
        
        /// <summary>
        /// g_fb21733c_7efc_42ed_8225_40283d08ac2c control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DocumentsSP.CustomWebPart.Carousel.Carousel g_fb21733c_7efc_42ed_8225_40283d08ac2c;
    }
}
