//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobikeSPO.SPOWebParts.IndexWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class IndexWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(IndexWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::MobikeSPO.SPOWebParts.IndexWebPart.IndexWebPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<link href=\"/_layouts/15/Content/MobikeHome.css\" rel=\"stylesheet\" />\r\n<script" +
                        " src=\"/_layouts/15/Scripts/MobikeHome.js\"></script>\r\n\r\n<div class=\"CanvasZone ms" +
                        "-Grid-row CanvasZone--read CanvasZone--centerAlign\">\r\n    <div class=\"CanvasSect" +
                        "ion ms-Grid-col ms-sm12 ms-xl8 CanvasSection--read\">\r\n        <div class=\"Contro" +
                        "lZone NoMTop\">\r\n            <div>\r\n                <div class=\"ControlZone-contr" +
                        "ol\">\r\n                    <div style=\"width: 100%;\">\r\n                        <d" +
                        "iv class=\"promptingTips\">\r\n                        </div>\r\n                     " +
                        "   <div class=\"realWebPart\">\r\n                            <div class=\"HTMLEmbed_" +
                        "11607c64\" style=\"max-width: 739px;\">\r\n                                <div role=" +
                        "\"row\" class=\"embedCode_11607c64\" tabindex=\"0\" aria-label=\"按 Enter 键或向下箭头键以输入嵌入的内" +
                        "容。\" style=\"padding-bottom: 56.2923%;\">\r\n                                    \r\n  " +
                        "                                  <video id=\"ctl00_ctl42_idPageMediaPlayer\" widt" +
                        "h=\"739\" height=\"416\" poster=\"\" autoplay=\"\" onloadstart=\"\" data-init=\"1\" controls" +
                        "=\"\">\r\n                                        <source src=\"/SPO/Videos/摩拜单车422一周" +
                        "年历程/摩拜单车422一周年历程.mp4\" data-label=\"\" type=\"video/mp4\">\r\n                         " +
                        "           </video>\r\n                                </div>\r\n                   " +
                        "             <div class=\"captionElement__caption_a52d03de captionElement__center" +
                        "Align_a52d03de\">\r\n                                    <span></span>\r\n           " +
                        "                     </div>\r\n                            </div>\r\n               " +
                        "         </div>\r\n                    </div>\r\n                </div>\r\n           " +
                        "     <div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        " +
                        "<!-- react-empty: 快速链接 -->\r\n        <div class=\"ControlZone\">\r\n            <div>" +
                        "\r\n                <div class=\"ControlZone-control\">\r\n                    <div st" +
                        "yle=\"width: 100%;\">\r\n                        <div class=\"webPartChrome_d27fb994\"" +
                        ">\r\n                            <div class=\"webPartHeader_d27fb994 headerLgMargin" +
                        "_d27fb994\">\r\n                                <div class=\"title_d27fb994 captionE" +
                        "lement__title_a52d03de captionElement__leftAlign_a52d03de\">\r\n                   " +
                        "                 <span>快速链接</span>\r\n                                </div>\r\n    " +
                        "                        </div>\r\n                            <div class=\"content_" +
                        "d27fb994\">\r\n                                <div>\r\n                             " +
                        "       <div>\r\n                                        <div class=\"ms-Fabric css-" +
                        "64\">\r\n                                            <div>\r\n                       " +
                        "                         <div role=\"presentation\" class=\"ms-FocusZone compactCar" +
                        "dLayout_6e9fe6ab Quick-links\">\r\n                                                " +
                        "</div>\r\n                                            </div>\r\n                    " +
                        "                    </div>\r\n                                    </div>\r\n        " +
                        "                        </div>\r\n                            </div>\r\n            " +
                        "            </div>\r\n                    </div>\r\n                </div>\r\n        " +
                        "    </div>\r\n        </div>\r\n        <!-- react-empty: 快速链接下分割线 -->\r\n        <div" +
                        " class=\"ControlZone\">\r\n            <div>\r\n                <div class=\"ControlZon" +
                        "e-control\">\r\n                    <div style=\"width: 100%;\">\r\n                   " +
                        "     <div aria-hidden=\"true\" class=\"dividerPlaceholder_cb20282c\" role=\"presentat" +
                        "ion\" tabindex=\"-1\">\r\n                            <hr aria-hidden=\"true\" class=\"d" +
                        "ivider_cb20282c\" role=\"presentation\">\r\n                        </div>\r\n         " +
                        "           </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n " +
                        "       <!-- react-empty: 最近使用的文档 -->\r\n        <div class=\"ControlZone\">\r\n       " +
                        "     <div>\r\n                <div class=\"ControlZone-control\">\r\n                 " +
                        "   <div style=\"width: 100%;\">\r\n                        <div class=\"webPartChrome" +
                        "_d27fb994\">\r\n                            <div class=\"webPartHeader_d27fb994 head" +
                        "erLgMargin_d27fb994\">\r\n                                <div class=\"title_d27fb99" +
                        "4 captionElement__title_a52d03de captionElement__leftAlign_a52d03de\">\r\n         " +
                        "                           <span>最近使用的文档</span>\r\n                               " +
                        " </div>\r\n                                <a aria-label=\"浏览所有项目\" class=\"ms-Link r" +
                        "oot_c02e569e seeAll_d27fb994 isEnabled_c02e569e\" href=\"/SPO/_layouts/15/SPOLates" +
                        "tFiles.aspx\">全部查看</a>\r\n                            </div>\r\n                     " +
                        "       <div class=\"content_d27fb994\">\r\n                                <div>\r\n  " +
                        "                                  <div>\r\n                                       " +
                        " <div class=\"ms-Fabric ListLayout_4665c459 css-64\" role=\"application\" aria-label" +
                        "=\"使用向上键和向下键浏览内容的网格行。按 Enter 键导航到内容 URL。\">\r\n                                     " +
                        "       <div class=\"ms-Viewport\" style=\"min-width: 1px; min-height: 1px;\">\r\n     " +
                        "                                           <div class=\"ms-DetailsList root_28415" +
                        "6b6 is-horizontalConstrained rootIsHorizontalConstrained_284156b6\">\r\n           " +
                        "                                         <div role=\"grid\" aria-rowcount=\"7\" aria" +
                        "-colcount=\"4\" aria-readonly=\"true\">\r\n                                           " +
                        "             <div role=\"presentation\">\r\n                                        " +
                        "                    <div role=\"row\" class=\"ms-FocusZone ms-DetailsHeader root_b7" +
                        "8ba6e1\">\r\n                                                                <div r" +
                        "ole=\"columnheader\" aria-sort=\"none\" aria-disabled=\"false\" aria-colindex=\"0\" clas" +
                        "s=\"ms-DetailsHeader-cell cell_b78ba6e1 is-actionable cellIsActionable_b78ba6e1 i" +
                        "s-empty cellIsEmpty_b78ba6e1\" data-automationid=\"ColumnsHeaderColumn\" data-item-" +
                        "key=\"column1\" style=\"width: 67px;\">\r\n                                           " +
                        "                         <span class=\"cellTooltip_b78ba6e1\">\r\n                  " +
                        "                                                      <span id=\"header13-column1" +
                        "\" aria-labelledby=\"header13-column1-name \" class=\"ms-DetailsHeader-cellTitle cel" +
                        "lTitle_b78ba6e1\" role=\"button\" aria-describedby=\"header13-column1-tooltip\" aria-" +
                        "haspopup=\"false\" tabindex=\"0\">\r\n                                                " +
                        "                            <span id=\"header13-column1-name\" class=\"ms-DetailsHe" +
                        "ader-cellName\"></span>\r\n                                                        " +
                        "                </span>\r\n                                                       " +
                        "             </span>\r\n                                                          " +
                        "      </div>\r\n                                                                <d" +
                        "iv aria-hidden=\"true\" role=\"button\" class=\"ms-DetailsHeader-cellSizer cellSizer_" +
                        "b78ba6e1\" tabindex=\"-1\">\r\n                                                      " +
                        "          </div>\r\n                                                              " +
                        "  <div role=\"columnheader\" aria-sort=\"none\" aria-disabled=\"false\" aria-colindex=" +
                        "\"1\" class=\"ms-DetailsHeader-cell cell_b78ba6e1 is-actionable cellIsActionable_b7" +
                        "8ba6e1\" style=\"width: 378px;\">\r\n                                                " +
                        "                    <span class=\"cellTooltip_b78ba6e1\">\r\n                       " +
                        "                                                 <span id=\"header13-column2\" ari" +
                        "a-labelledby=\"header13-column2-name \" class=\"ms-DetailsHeader-cellTitle cellTitl" +
                        "e_b78ba6e1\" data-is-focusable=\"true\" role=\"button\" aria-describedby=\"header13-co" +
                        "lumn2-tooltip\" aria-haspopup=\"false\" tabindex=\"-1\">\r\n                           " +
                        "                                                 <span id=\"header13-column2-name" +
                        "\" class=\"ms-DetailsHeader-cellName\">\r\n                                          " +
                        "                                      <!-- react-text: 17 -->\r\n                 " +
                        "                                                               标题<!-- /react-tex" +
                        "t --></span>\r\n                                                                  " +
                        "      </span>\r\n                                                                 " +
                        "   </span>\r\n                                                                </di" +
                        "v>\r\n                                                                <div aria-hi" +
                        "dden=\"true\" role=\"button\" data-is-focusable=\"false\" data-sizer-index=\"1\" class=\"" +
                        "ms-DetailsHeader-cellSizer cellSizer_b78ba6e1\" tabindex=\"-1\">\r\n                 " +
                        "                                               </div>\r\n                         " +
                        "                                       <div role=\"columnheader\" aria-sort=\"none\"" +
                        " aria-disabled=\"false\" aria-colindex=\"2\" class=\"ms-DetailsHeader-cell cell_b78ba" +
                        "6e1 is-actionable cellIsActionable_b78ba6e1\" data-automationid=\"ColumnsHeaderCol" +
                        "umn\" data-item-key=\"column3\" style=\"width: 116px;\">\r\n                           " +
                        "                                         <span class=\"cellTooltip_b78ba6e1\">\r\n  " +
                        "                                                                      <span id=\"" +
                        "header13-column3\" aria-labelledby=\"header13-column3-name \" class=\"ms-DetailsHead" +
                        "er-cellTitle cellTitle_b78ba6e1\" data-is-focusable=\"true\" role=\"button\" aria-des" +
                        "cribedby=\"header13-column3-tooltip\" aria-haspopup=\"false\" tabindex=\"-1\">\r\n      " +
                        "                                                                      <span id=\"" +
                        "header13-column3-name\" class=\"ms-DetailsHeader-cellName\">\r\n                     " +
                        "                                                           <!-- react-text: 23 -" +
                        "->\r\n                                                                            " +
                        "    已修改<!-- /react-text --></span>\r\n                                            " +
                        "                            </span>\r\n                                           " +
                        "                         </span>\r\n                                              " +
                        "                  </div>\r\n                                                      " +
                        "          <div aria-hidden=\"true\" role=\"button\" data-is-focusable=\"false\" data-s" +
                        "izer-index=\"2\" class=\"ms-DetailsHeader-cellSizer cellSizer_b78ba6e1\" tabindex=\"-" +
                        "1\">\r\n                                                                </div>\r\n   " +
                        "                                                             <div role=\"columnhe" +
                        "ader\" aria-sort=\"none\" aria-disabled=\"false\" aria-colindex=\"3\" class=\"ms-Details" +
                        "Header-cell cell_b78ba6e1 is-actionable cellIsActionable_b78ba6e1\" data-automati" +
                        "onid=\"ColumnsHeaderColumn\" data-item-key=\"column4\" style=\"width: 166px;\">\r\n     " +
                        "                                                               <span class=\"cell" +
                        "Tooltip_b78ba6e1\">\r\n                                                            " +
                        "            <span id=\"header13-column4\" aria-labelledby=\"header13-column4-name \"" +
                        " class=\"ms-DetailsHeader-cellTitle cellTitle_b78ba6e1\" data-is-focusable=\"true\" " +
                        "role=\"button\" aria-describedby=\"header13-column4-tooltip\" aria-haspopup=\"false\" " +
                        "tabindex=\"-1\">\r\n                                                                " +
                        "            <span id=\"header13-column4-name\" class=\"ms-DetailsHeader-cellName\">\r" +
                        "\n                                                                               " +
                        " <!-- react-text: 29 -->\r\n                                                      " +
                        "                          修改者<!-- /react-text --></span>\r\n                      " +
                        "                                                  </span>\r\n                     " +
                        "                                               </span>\r\n                        " +
                        "                                        </div>\r\n                                " +
                        "                                <div aria-hidden=\"true\" role=\"button\" data-is-fo" +
                        "cusable=\"false\" data-sizer-index=\"3\" class=\"ms-DetailsHeader-cellSizer cellSizer" +
                        "_b78ba6e1\" tabindex=\"-1\">\r\n                                                     " +
                        "           </div>\r\n                                                            <" +
                        "/div>\r\n                                                        </div>\r\n         " +
                        "                                               <div role=\"presentation\">\r\n      " +
                        "                                                      <div role=\"presentation\" c" +
                        "lass=\"ms-FocusZone focusZone_284156b6\" data-focuszone-id=\"FocusZone15\">\r\n       " +
                        "                                                         <div class=\"ms-Selectio" +
                        "nZone\" role=\"presentation\">\r\n                                                   " +
                        "                 <div role=\"presentation\" class=\"ms-List\">\r\n                    " +
                        "                                                    <div class=\"ms-List-surface\"" +
                        " role=\"presentation\">\r\n                                                         " +
                        "                   <div class=\"ms-List-page _Documents\" role=\"presentation\">\r\n  " +
                        "                                                                          </div>" +
                        "\r\n                                                                        </div>" +
                        "\r\n                                                                    </div>\r\n  " +
                        "                                                              </div>\r\n          " +
                        "                                                  </div>\r\n                      " +
                        "                                  </div>\r\n                                      " +
                        "              </div>\r\n                                                </div>\r\n  " +
                        "                                          </div>\r\n                              " +
                        "          </div>\r\n                                    </div>\r\n                  " +
                        "              </div>\r\n                            </div>\r\n                      " +
                        "  </div>\r\n                    </div>\r\n                </div>\r\n            </div>" +
                        "\r\n        </div>\r\n    </div>\r\n    <div class=\"CanvasSection ms-Grid-col ms-sm12 " +
                        "ms-xl4 CanvasSection--read\">\r\n        <!-- react-empty:公告 -->\r\n        <div aria" +
                        "-labelledby=\"cswpAccessibleLabelContextual_82f13ef7-ca1b-4d21-bb83-bf2a253e0f25\"" +
                        " class=\"ControlZone NoMTop\" data-sp-a11y-id=\"ControlZone_82f13ef7-ca1b-4d21-bb83" +
                        "-bf2a253e0f25\">\r\n            <div>\r\n                <div class=\"ControlZone-cont" +
                        "rol\">\r\n                    <div style=\"width: 100%;\">\r\n                        <" +
                        "div class=\"webPartChrome_d27fb994\">\r\n                            <div class=\"web" +
                        "PartHeader_d27fb994 headerLgMargin_d27fb994\">\r\n                                <" +
                        "div class=\"title_d27fb994 captionElement__title_a52d03de captionElement__leftAli" +
                        "gn_a52d03de\">\r\n                                    <span>公告</span>\r\n            " +
                        "                    </div>\r\n                                <a aria-label=\"查看所有公" +
                        "告\" class=\"ms-Link root_c02e569e seeAll_d27fb994 isEnabled_c02e569e\" data-automat" +
                        "ion-id=\"newsSeeAllLink\" href=\"/SPO/_layouts/15/NoticeList.aspx\">查看全部</a>\r\n      " +
                        "                      </div>\r\n                            <div class=\"content_d2" +
                        "7fb994\">\r\n                                <div>\r\n                               " +
                        "     <div>\r\n                                        <div class=\"listNewsLayout_1" +
                        "199886e listNewsLayout__small_1199886e\" data-automation-id=\"listNewsLayout\">\r\n  " +
                        "                                          <div role=\"list\" aria-label=\"公告\">\r\n   " +
                        "                                             <div role=\"list\" class=\"ms-List\">\r\n" +
                        "                                                    <div class=\"ms-List-surface\"" +
                        " role=\"presentation\">\r\n                                                        <" +
                        "div class=\"ms-List-page TheSign\" role=\"presentation\">\r\n                         " +
                        "                               </div>\r\n                                         " +
                        "           </div>\r\n                                                </div>\r\n     " +
                        "                                       </div>\r\n                                 " +
                        "       </div>\r\n                                    </div>\r\n                     " +
                        "           </div>\r\n                            </div>\r\n                        <" +
                        "/div>\r\n                    </div>\r\n                </div>\r\n                <div>" +
                        "\r\n                    <!-- react-empty: 46 -->\r\n                </div>\r\n        " +
                        "    </div>\r\n        </div>\r\n        <!-- react-empty: 问卷调查 -->\r\n        <div ari" +
                        "a-labelledby=\"cswpAccessibleLabelContextual_7c6602b2-34a5-4132-87cf-bb243cd82b7e" +
                        "\" class=\"ControlZone\" data-sp-a11y-id=\"ControlZone_7c6602b2-34a5-4132-87cf-bb243" +
                        "cd82b7e\">\r\n            <div>\r\n                <div class=\"ControlZone-control\">\r" +
                        "\n                    <div style=\"width: 100%;\">\r\n                        <div cl" +
                        "ass=\"webPartChrome_d27fb994\">\r\n                            <div class=\"webPartHe" +
                        "ader_d27fb994 headerLgMargin_d27fb994\">\r\n                                <div cl" +
                        "ass=\"title_d27fb994 captionElement__title_a52d03de captionElement__leftAlign_a52" +
                        "d03de\">\r\n                                    <span>问卷调查</span>\r\n                " +
                        "                </div>\r\n                            </div>\r\n                    " +
                        "        <div class=\"content_d27fb994\">\r\n                                <div>\r\n " +
                        "                                   <div>\r\n                                      " +
                        "  <div role=\"application\" style=\"max-width: 353.328px;\">\r\n                      " +
                        "                      <div class=\"carouselContainer_0bebf960 filmStrip_0bebf960\"" +
                        ">\r\n                                                <div class=\"slick-initialized" +
                        " slick-slider\">\r\n                                                    <div class=" +
                        "\"slick-list\">\r\n                                                        <div clas" +
                        "s=\"slick-track\" style=\"opacity: 1; transform: translate3d(0px, 0px, 0px); width:" +
                        " 1119.94px;\">\r\n                                                            <div " +
                        "data-index=\"0\" class=\"slick-slide slick-active\" tabindex=\"0\" style=\"outline: non" +
                        "e; width: 373.313px;\">\r\n                                                        " +
                        "        <a role=\"listitem\" href=\"https://mobike-my.sharepoint.cn/personal/liuxin" +
                        "gshun_mobike_com/_layouts/15/guestaccess.aspx?guestaccesstoken=hiDSGrxm0FTYxaVvO" +
                        "8bO5i0HuM3yhyuk7Lk2FEG1qHs%3d&amp;docid=1_151d5e02a3677411d94ee991b534faa0b&amp;" +
                        "wdFormId=%7b81CD6C49-B407-4F62-8901-5548DDBA4750%7d&amp;web=1\" target=\"_self\" cl" +
                        "ass=\"quickItemTile_f24d7c74\" aria-label=\"向我们反馈站点使用中的问题，列表中的第 1 个链接(共 1 个)。 图像: 邀" +
                        "请小伙伴反馈使用中的问题。\" tabindex=\"0\">\r\n                                                  " +
                        "                  <div role=\"presentation\" class=\"ms-FocusZone\" data-focuszone-i" +
                        "d=\"FocusZone23\">\r\n                                                              " +
                        "          <div class=\"ms-DocumentCard root_118a77a5\">\r\n                         " +
                        "                                                   <div class=\"ms-DocumentCardPr" +
                        "eview preview_118a77a5\">\r\n                                                      " +
                        "                          <div>\r\n                                               " +
                        "                                     <div class=\"ms-Image root_031d536a\" style=\"" +
                        "width: 353.328px; height: 198.747px;\">\r\n                                        " +
                        "                                                <img src=\"/_layouts/15/Images/we" +
                        "njuan.jpg\" role=\"presentation\" alt=\"\" class=\"ms-Image-image image_031d536a ms-Im" +
                        "age-image--portrait imageIsPortrait_031d536a ms-Image-image--cover imageIsCover_" +
                        "031d536a is-loaded imageIsLoaded_031d536a is-fadeIn css-67\">\r\n                  " +
                        "                                                                  </div>\r\n      " +
                        "                                                                          </div>" +
                        "\r\n                                                                            </" +
                        "div>\r\n                                                                          " +
                        "  <div class=\"tilePlateArea_f24d7c74\">\r\n                                        " +
                        "                                        <div data-automation-id=\"less-text\" clas" +
                        "s=\"lessText_e036c8c9 tileText_f24d7c74\">\r\n                                      " +
                        "                                              向我们反馈站点使用中的问题\r\n                   " +
                        "                                                             </div>\r\n           " +
                        "                                                                 </div>\r\n       " +
                        "                                                                 </div>\r\n       " +
                        "                                                             </div>\r\n           " +
                        "                                                     </a>\r\n                     " +
                        "                                       </div>\r\n                                 " +
                        "                       </div>\r\n                                                 " +
                        "   </div>\r\n                                                </div>\r\n             " +
                        "                               </div>\r\n                                         " +
                        "   <div class=\"screenReaderOnly_0bebf960\" id=\"469bffaf-04c0-4a88-9650-1cef9640f2" +
                        "30-focusZone\">\r\n                                                使用向右键和向左键可在传送中的图" +
                        "像之间导航。\r\n                                            </div>\r\n                    " +
                        "                    </div>\r\n                                    </div>\r\n        " +
                        "                        </div>\r\n                            </div>\r\n            " +
                        "            </div>\r\n                    </div>\r\n                </div>\r\n        " +
                        "        <div>\r\n                    <!-- react-empty: 53 -->\r\n                </d" +
                        "iv>\r\n            </div>\r\n        </div>\r\n        <!-- react-empty: 通讯录 -->\r\n    " +
                        "    <div aria-labelledby=\"cswpAccessibleLabelContextual_3d699356-e495-4eb5-b05c-" +
                        "0c5c813ee291\" class=\"ControlZone\" data-sp-a11y-id=\"ControlZone_3d699356-e495-4eb" +
                        "5-b05c-0c5c813ee291\">\r\n            <div>\r\n                <div class=\"ControlZon" +
                        "e-control\">\r\n                    <div style=\"width: 100%;\">\r\n                   " +
                        "     <div class=\"imageGallery_9d1054de\">\r\n                            <div class" +
                        "=\"titlePadding_9d1054de\">\r\n                                <div class=\"captionEl" +
                        "ement__title_a52d03de captionElement__leftAlign_a52d03de\">\r\n                    " +
                        "                <span>通讯录</span>\r\n                                </div>\r\n      " +
                        "                      </div>\r\n                            <div role=\"application" +
                        "\" style=\"max-width: 353.328px;\">\r\n                                <div class=\"ca" +
                        "rouselContainer_0bebf960 Address-Book\">\r\n                                </div>\r" +
                        "\n                            </div>\r\n                        </div>\r\n           " +
                        "         </div>\r\n                </div>\r\n                <div>\r\n                " +
                        "    <!-- react-empty: 60 -->\r\n                </div>\r\n            </div>\r\n      " +
                        "  </div>\r\n        <!-- react-empty: 61 -->\r\n    </div>\r\n    <!-- react-empty: 62" +
                        " -->\r\n</div>\r\n<div class=\"CanvasZoneContainer CanvasZoneContainer--read\" data-ne" +
                        "gative-space=\"true\">\r\n    <div class=\"CanvasZone ms-Grid-row CanvasZone--read Ca" +
                        "nvasZone--centerAlign\" data-automation-id=\"CanvasZone\" data-drag-tag=\"CanvasZone" +
                        "\" data-negative-space=\"true\" data-sp-a11y-id=\"CanvasZone_3\">\r\n        <div class" +
                        "=\"CanvasSection ms-Grid-col ms-sm12 ms-xl12 CanvasSection--read\">\r\n            <" +
                        "!-- react-empty: 67 -->\r\n            <div aria-labelledby=\"cswpAccessibleLabelCo" +
                        "ntextual_7c553c79-3d95-4296-a41e-e4c22c69f3c2\" class=\"ControlZone\" data-sp-a11y-" +
                        "id=\"ControlZone_7c553c79-3d95-4296-a41e-e4c22c69f3c2\">\r\n                <div>\r\n " +
                        "                   <div class=\"ControlZone-control\">\r\n                        <d" +
                        "iv style=\"width: 100%;\">\r\n                            <div class=\"ms-Fabric css-" +
                        "64\">\r\n                                <div class=\"embedContainer_2126e996\">\r\n   " +
                        "                                 <div>\r\n                                        " +
                        "<div class=\"ms-Fabric bingPreview_ce375070 css-64\">\r\n                           " +
                        "                 <a class=\"thumbnailLink_ce375070\" href=\"https://mobike.com/cn/\"" +
                        " target=\"_blank\">\r\n                                                <div class=\"m" +
                        "s-Image root_031d536a thumbnailContainer_ce375070\" style=\"width: 240px; height: " +
                        "135px;\">\r\n                                                    <img class=\"ms-Ima" +
                        "ge-image image_031d536a ms-Image-image--landscape imageIsLandscape_031d536a ms-I" +
                        "mage-image--cover imageIsCover_031d536a is-loaded imageIsLoaded_031d536a is-fade" +
                        "In css-70\" src=\"/_layouts/15/Images/mologo.png\" title=\"Mobike\">\r\n               " +
                        "                                 </div>\r\n                                       " +
                        "     </a>\r\n                                            <div class=\"metadata_ce37" +
                        "5070\">\r\n                                                <a class=\"ms-Link root_c" +
                        "02e569e titleContainer_ce375070 isEnabled_c02e569e\" href=\"https://mobike.com/cn/" +
                        "\" target=\"_blank\">\r\n                                                    <div dat" +
                        "a-automation-id=\"less-text\" title=\"Mobike\" class=\"lessText_e036c8c9 metadataTitl" +
                        "e_ce375070\">\r\n                                                        Mobike\r\n  " +
                        "                                                  </div>\r\n                      " +
                        "                          </a>\r\n                                                " +
                        "<div class=\"metadataSubtitle_ce375070\">\r\n                                       " +
                        "             mobike.com\r\n                                                </div>\r" +
                        "\n                                                <div class=\"metadataDescription" +
                        "_ce375070\" title=\"京 icp 备15053449 号 京公网安备 11010502032956 号 增值电信业务经营许可证编号：京b2-201" +
                        "70053\">\r\n                                                    京 icp 备15053449 号 京" +
                        "公网安备 11010502032956 号 增值电信业务经营许可证编号：京b2-20170053\r\n                              " +
                        "                  </div>\r\n                                            </div>\r\n  " +
                        "                                      </div>\r\n                                  " +
                        "  </div>\r\n                                </div>\r\n                              " +
                        "  <div class=\"screenReaderAlert_a7118188\">\r\n                                </di" +
                        "v>\r\n                                <div class=\"screenReaderAlert_a7118188\">\r\n  " +
                        "                              </div>\r\n                            </div>\r\n      " +
                        "                  </div>\r\n                    </div>\r\n                    <div>\r" +
                        "\n                        <!-- react-empty: 73 -->\r\n                    </div>\r\n " +
                        "               </div>\r\n            </div>\r\n            <!-- react-empty: 74 -->\r" +
                        "\n        </div>\r\n        <!-- react-empty: 75 -->\r\n    </div>\r\n</div>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
