//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsSP.CustomWebPart.Left {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class Left {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(Left target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::DocumentsSP.CustomWebPart.Left.Left @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<style>\r\n    .HotTab, .TopTab {\r\n        display: block;\r\n        overflow: h" +
                        "idden;\r\n        margin-bottom: 10px;\r\n        border-bottom: 1px solid #eee;\r\n  " +
                        "  }\r\n\r\n    .Htab_bt, .Ttab_bt {\r\n        float: left;\r\n        width: 150px;\r\n  " +
                        "      height: 36px;\r\n        box-sizing: border-box;\r\n        line-height: 36px;" +
                        "\r\n        margin-right: 10px;\r\n        text-align: center;\r\n        cursor: poin" +
                        "ter;\r\n    }\r\n\r\n    .noBorderRight {\r\n        border-right: none;\r\n    }\r\n\r\n    ." +
                        "Htab-active, .Ttab-active {\r\n        border-bottom: 3px solid #0E60AC;\r\n    }\r\n\r" +
                        "\n    .HotContent, .TopContent {\r\n        width: 100%;\r\n        height: 535px;\r\n " +
                        "       overflow: hidden;\r\n    }\r\n\r\n        .HotContent .detail, .TopContent .det" +
                        "ail {\r\n            height: 500px;\r\n            overflow: hidden;\r\n        }\r\n\r\n " +
                        "       .HotContent .more, .TopContent .more {\r\n            text-align: right;\r\n " +
                        "           padding: 0 10px;\r\n        }\r\n\r\n    .Hcon_detail, .Tcon_detail {\r\n    " +
                        "    display: none;\r\n        width: 100%;\r\n        height: 100%;\r\n    }\r\n\r\n    .s" +
                        "how {\r\n        display: block;\r\n    }\r\n\r\n    .more img {\r\n        width: 46px;\r\n" +
                        "        height: 7px;\r\n    }\r\n\r\n    .detail img {\r\n        margin-right: 10px;\r\n " +
                        "   }\r\n\r\n    .a_folder {\r\n        margin-right: 50px;\r\n    }\r\n</style>\r\n\r\n<div st" +
                        "yle=\"width: 650px; height: 580px;\">\r\n    <div class=\"HotTab\">\r\n        <div clas" +
                        "s=\"Htab_bt Htab-active noBorderRight\">Latest</div>\r\n        <div class=\"Htab_bt " +
                        "noBorderRight\">Most Downloads</div>\r\n        <div class=\"Htab_bt noBorderRight\">" +
                        "Common</div>\r\n        <div class=\"Htab_bt\">Region</div>\r\n    </div>\r\n    <div cl" +
                        "ass=\"HotContent\">\r\n        <div class=\"Hcon_detail show\">\r\n            <div id=\"" +
                        "LatestFileJson\" class=\"detail\"></div>\r\n            <div class=\"more\">\r\n         " +
                        "       <a href=\"/_layouts/15/LatestFiles.aspx\" title=\"More\">\r\n                  " +
                        "  <img src=\"/_layouts/15/images/more.png\" />\r\n                </a>\r\n            " +
                        "</div>\r\n        </div>\r\n        <div class=\"Hcon_detail\">\r\n            <div id=\"" +
                        "MostDownLoadFileJson\" class=\"detail\"></div>\r\n            <div class=\"more\">\r\n   " +
                        "             <a href=\"/_layouts/15/MostDownLoadFiles.aspx\" title=\"More\">\r\n      " +
                        "              <img src=\"/_layouts/15/images/more.png\" />\r\n                </a>\r\n" +
                        "            </div>\r\n        </div>\r\n        <div class=\"Hcon_detail\">\r\n         " +
                        "   <div id=\"CommonFileJson\" class=\"detail\"></div>\r\n            <div class=\"more\"" +
                        ">\r\n                <a href=\"/Documents/Forms/AllItems.aspx?RootFolder=/Documents" +
                        "/Common\" title=\"More\">\r\n                    <img src=\"/_layouts/15/images/more.p" +
                        "ng\" />\r\n                </a>\r\n            </div>\r\n        </div>\r\n         <div " +
                        "class=\"Hcon_detail\">\r\n            <div id=\"RegionFileJson\" class=\"detail\"></div>" +
                        "\r\n            <div class=\"more\">\r\n                <a href=\"/_layouts/15/RegionFi" +
                        "les.aspx\" title=\"More\">\r\n                    <img src=\"/_layouts/15/images/more." +
                        "png\" />\r\n                </a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n<" +
                        "/div>\r\n<script>\r\n    $(document).ready(function () {\r\n        var tabH = $(\".Hta" +
                        "b_bt\");\r\n        for (var i = 0; i < tabH.length; i++) {\r\n            tabH[i].in" +
                        "dex = i;\r\n            tabH[i].onclick = function () {\r\n                $(this).a" +
                        "ddClass(\'Htab-active\').siblings().removeClass(\'Htab-active\');\r\n                $" +
                        "(\".Hcon_detail:eq(\" + this.index + \")\").addClass(\'show\').siblings().removeClass(" +
                        "\'show\');\r\n            };\r\n        }\r\n\r\n        $.ajax({\r\n            type: \"post" +
                        "\",\r\n            url: \"/_layouts/15/WebPartContent.aspx/GetLatestFileJson\",\r\n    " +
                        "        data: \"\",\r\n            contentType: \"application/json;charset=utf-8\",\r\n " +
                        "           dataType: \"json\",\r\n            success: function (response, textStatu" +
                        "s) {\r\n                $(\"#LatestFileJson\").html(response.d);\r\n            },\r\n  " +
                        "          error: function (XMLHttpRequest, textStatus, errorThrown) {\r\n         " +
                        "       console.log(textStatus);\r\n            }\r\n        });\r\n\r\n        $.ajax({\r" +
                        "\n            type: \"post\",\r\n            url: \"/_layouts/15/WebPartContent.aspx/G" +
                        "etMostDownLoadFileJson\",\r\n            data: \"\",\r\n            contentType: \"appli" +
                        "cation/json;charset=utf-8\",\r\n            dataType: \"json\",\r\n            success:" +
                        " function (response, textStatus) {\r\n                $(\"#MostDownLoadFileJson\").h" +
                        "tml(response.d);\r\n            },\r\n            error: function (XMLHttpRequest, t" +
                        "extStatus, errorThrown) {\r\n                console.log(textStatus);\r\n           " +
                        " }\r\n        });\r\n\r\n        $.ajax({\r\n            type: \"post\",\r\n            url:" +
                        " \"/_layouts/15/WebPartContent.aspx/GetCommonFileJson\",\r\n            data: \"\",\r\n " +
                        "           contentType: \"application/json;charset=utf-8\",\r\n            dataType:" +
                        " \"json\",\r\n            success: function (response, textStatus) {\r\n              " +
                        "  $(\"#CommonFileJson\").html(response.d);\r\n            },\r\n            error: fun" +
                        "ction (XMLHttpRequest, textStatus, errorThrown) {\r\n                console.log(t" +
                        "extStatus);\r\n            }\r\n        });\r\n\r\n        $.ajax({\r\n            type: \"" +
                        "post\",\r\n            url: \"/_layouts/15/WebPartContent.aspx/GetRegionFilesJson\",\r" +
                        "\n            data: \"\",\r\n            contentType: \"application/json;charset=utf-8" +
                        "\",\r\n            dataType: \"json\",\r\n            success: function (response, text" +
                        "Status) {\r\n                $(\"#RegionFileJson\").html(response.d);\r\n            }" +
                        ",\r\n            error: function (XMLHttpRequest, textStatus, errorThrown) {\r\n    " +
                        "            console.log(textStatus);\r\n            }\r\n        });\r\n    });\r\n</scr" +
                        "ipt>\r\n\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
